=== xkovl007/NastaveniProgramu/nastaveni.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="rootType"/>
  <xs:complexType name="fontType">
    <xs:sequence>
      <xs:element type="standardniType" name="standardni"/>
      <xs:element type="vybranoType" name="vybrano"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="povolitObrazkyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="zobrazitPopisek" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="nastaveniType">
    <xs:sequence>
      <xs:element type="rozhraniType" name="rozhrani"/>
      <xs:element type="sitType" name="sit"/>
      <xs:element type="tiskType" name="tisk"/>
      <xs:element type="xs:byte" name="pocetZpracovavanychVlaken"/>
      <xs:element type="komprimovatVystupType" name="komprimovatVystup"/>
      <xs:element type="xs:boolean" name="povolitPluginy"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="poprediType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="typ" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="vybranoType">
    <xs:sequence>
      <xs:element name="nazev">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Consolas"/>
            <xs:enumeration value="Arial"/>
            <xs:enumeration value="Courier"/>
            <xs:enumeration value="Monospaced"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:byte" name="velikost"/>
      <xs:element type="poprediType" name="popredi"/>
      <xs:element type="pozadiType" name="pozadi"/>
      <xs:element name="styl">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Normalni"/>
            <xs:enumeration value="Tucne"/>
            <xs:enumeration value="Kurziva"/>
            <xs:enumeration value="Podtrzene"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="zarovnani">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Stred"/>
            <xs:enumeration value="Vlevo"/>
            <xs:enumeration value="Vpravo"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="zalamovaniRadkuType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="zobrazitSymbol" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="pozadiType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="typ" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="cislovatZaznamyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:short" name="start" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rozliseniType">
    <xs:simpleContent>
      <xs:extension base="xs:short">
        <xs:attribute type="xs:string" name="jednotka" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="nahoreType">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute type="xs:string" name="jednotka" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="okrajeType">
    <xs:sequence>
      <xs:element type="vlevoType" name="vlevo"/>
      <xs:element type="vpravoType" name="vpravo"/>
      <xs:element type="nahoreType" name="nahore"/>
      <xs:element type="doleType" name="dole"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="uvodniStranka" use="optional"/>
    <xs:attribute type="xs:string" name="zobrazitOkraje" use="optional"/>
  </xs:complexType>
  <xs:complexType name="korekceType">
    <xs:sequence>
      <xs:element type="xs:float" name="jas"/>
      <xs:element type="xs:float" name="kontrast"/>
      <xs:element type="xs:float" name="gamma"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="zaznamyType">
    <xs:sequence>
      <xs:element type="xs:short" name="maxPocetNaStranku"/>
      <xs:element type="xs:boolean" name="radit"/>
      <xs:element name="typRazeni">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Sestupne"/>
            <xs:enumeration value="Vzestupne"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="metodaVystupu">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="HTML"/>
            <xs:enumeration value="PDF"/>
            <xs:enumeration value="CSV"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="povolitObrazkyType" name="povolitObrazky"/>
      <xs:element name="zakladniMena">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="JPY"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="zalamovaniRadkuType" name="zalamovaniRadku"/>
      <xs:element name="znakovaSada">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Unicode"/>
            <xs:enumeration value="UTF-8"/>
            <xs:enumeration value="UTF-16"/>
            <xs:enumeration value="ASCII"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="cislovatZaznamyType" name="cislovatZaznamy"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="kontrolovatAktualizaceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:short" name="priXSpusteni" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="vpravoType">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute type="xs:string" name="jednotka" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="nastaveniType" name="nastaveni" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="menuBarType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="plovouci" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="komprimovatVystupType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="format" use="optional"/>
        <xs:attribute type="xs:byte" name="miraKomprese" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="doleType">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute type="xs:string" name="jednotka" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rozhraniType">
    <xs:sequence>
      <xs:element type="fontType" name="font"/>
      <xs:element type="zaznamyType" name="zaznamy"/>
      <xs:element type="xs:boolean" name="zobrazitTipy"/>
      <xs:element type="xs:short" name="preferovanaSirka"/>
      <xs:element type="xs:short" name="preferovanaVyska"/>
      <xs:element type="menuBarType" name="menuBar"/>
      <xs:element type="xs:boolean" name="animaceIkon"/>
      <xs:element name="barevneSchema">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Modre"/>
            <xs:enumeration value="Bile"/>
            <xs:enumeration value="Sede"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="jazyk">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CZ"/>
            <xs:enumeration value="EN"/>
            <xs:enumeration value="SK"/>
            <xs:enumeration value="JP"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tiskType">
    <xs:sequence>
      <xs:element type="rozliseniType" name="rozliseni"/>
      <xs:element name="barevnost">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Barva"/>
            <xs:enumeration value="Cernobile"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="format">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="A4"/>
            <xs:enumeration value="A5"/>
            <xs:enumeration value="A6"/>
            <xs:enumeration value="A3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="orientace">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Sirka"/>
            <xs:enumeration value="Vyska"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="kvalita">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Vysoka"/>
            <xs:enumeration value="Nizka"/>
            <xs:enumeration value="Standardni"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:boolean" name="duplex"/>
      <xs:element type="okrajeType" name="okraje"/>
      <xs:element name="barevnyModel">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CMYK"/>
            <xs:enumeration value="HSV"/>
            <xs:enumeration value="RGB"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="korekceType" name="korekce"/>
      <xs:element type="xs:boolean" name="orezoveZnacky"/>
      <xs:element type="xs:boolean" name="cislaStran"/>
      <xs:element type="xs:short" name="pocetKopii"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sitType">
    <xs:sequence>
      <xs:element type="kontrolovatAktualizaceType" name="kontrolovatAktualizace"/>
      <xs:element type="xs:short" name="citacSpusteni"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="vlevoType">
    <xs:simpleContent>
      <xs:extension base="xs:float">
        <xs:attribute type="xs:string" name="jednotka" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="standardniType">
    <xs:sequence>
      <xs:element name="nazev">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Consolas"/>
            <xs:enumeration value="Arial"/>
            <xs:enumeration value="Helvetica"/>
            <xs:enumeration value="Courier"/>
            <xs:enumeration value="Monospaced"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:byte" name="velikost"/>
      <xs:element type="poprediType" name="popredi"/>
      <xs:element type="pozadiType" name="pozadi"/>
      <xs:element name="styl">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Normalni"/>
            <xs:enumeration value="Tucne"/>
            <xs:enumeration value="Kurziva"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="zarovnani">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Stred"/>
            <xs:enumeration value="Vlevo"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== xkovl007/NastaveniProgramu/nastaveni.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nastaveni.xsd">
    <nastaveni>
        <rozhrani>
            <font>
                <standardni>
                    <nazev>Consolas</nazev>
                    <velikost>16</velikost>
                    <popredi typ="hex">#212110</popredi>
                    <pozadi typ="hex">#141426</pozadi>
                    <styl>Normalni</styl>
                    <zarovnani>Stred</zarovnani>
                </standardni>
                <vybrano>
                    <nazev>Consolas</nazev>
                    <velikost>16</velikost>
                    <popredi typ="hex">#2424E1</popredi>
                    <pozadi typ="hex">#1525D5</pozadi>
                    <styl>Tucne</styl>
                    <zarovnani>Stred</zarovnani>
                </vybrano>
            </font>
            <zaznamy>
                <maxPocetNaStranku>100</maxPocetNaStranku>
                <radit>true</radit>
                <typRazeni>Sestupne</typRazeni>
                <metodaVystupu>HTML</metodaVystupu>
                <povolitObrazky zobrazitPopisek="true">true</povolitObrazky>
                <zakladniMena>CZK</zakladniMena>
                <zalamovaniRadku zobrazitSymbol="true">true</zalamovaniRadku>
                <znakovaSada>Unicode</znakovaSada>
                <cislovatZaznamy start="1">true</cislovatZaznamy>
            </zaznamy>
            <zobrazitTipy>false</zobrazitTipy>
            <preferovanaSirka>800</preferovanaSirka>
            <preferovanaVyska>600</preferovanaVyska>
            <menuBar plovouci="true">true</menuBar>
            <animaceIkon>false</animaceIkon>
            <barevneSchema>Modre</barevneSchema>
            <jazyk>CZ</jazyk>
        </rozhrani>
        <sit>
            <kontrolovatAktualizace priXSpusteni="5">true</kontrolovatAktualizace>
            <citacSpusteni>1</citacSpusteni>
        </sit>
        <tisk>
            <rozliseni jednotka="pix/inch">300</rozliseni>
            <barevnost>Barva</barevnost>
            <format>A4</format>
            <orientace>Sirka</orientace>
            <kvalita>Vysoka</kvalita>
            <duplex>false</duplex>
            <okraje uvodniStranka="true" zobrazitOkraje="false">
                <vlevo jednotka="cm">2.5</vlevo>
                <vpravo jednotka = "cm">2.5</vpravo>
                <nahore jednotka="cm">2.5</nahore>
                <dole jednotka="cm">2.5</dole>
            </okraje>
            <barevnyModel>CMYK</barevnyModel>
            <korekce>
                <jas>0.5</jas>
                <kontrast>0.5</kontrast>
                <gamma>0.5</gamma>
            </korekce>
            <orezoveZnacky>false</orezoveZnacky>
            <cislaStran>true</cislaStran>
            <pocetKopii>1</pocetKopii>
        </tisk>
        <pocetZpracovavanychVlaken>2</pocetZpracovavanychVlaken>
        <komprimovatVystup format="zip" miraKomprese="2">true</komprimovatVystup>
        <povolitPluginy>true</povolitPluginy>
    </nastaveni>
    <nastaveni>
        <rozhrani>
            <font>
                <standardni>
                    <nazev>Arial</nazev>
                    <velikost>18</velikost>
                    <popredi typ="dec">10,15,200</popredi>
                    <pozadi typ="dec">12,11,16</pozadi>
                    <styl>Tucne</styl>
                    <zarovnani>Vlevo</zarovnani>
                </standardni>
                <vybrano>
                    <nazev>Arial</nazev>
                    <velikost>19</velikost>
                    <popredi typ="dec">16,12,15</popredi>
                    <pozadi typ="dec">87,161,19</pozadi>
                    <styl>Tucne</styl>
                    <zarovnani>Vlevo</zarovnani>
                </vybrano>
            </font>
            <zaznamy>
                <maxPocetNaStranku>10</maxPocetNaStranku>
                <radit>true</radit>
                <typRazeni>Vzestupne</typRazeni>
                <metodaVystupu>PDF</metodaVystupu>
                <povolitObrazky zobrazitPopisek="false">true</povolitObrazky>
                <zakladniMena>EUR</zakladniMena>
                <zalamovaniRadku zobrazitSymbol="false">true</zalamovaniRadku>
                <znakovaSada>UTF-8</znakovaSada>
                <cislovatZaznamy start="100">true</cislovatZaznamy>
            </zaznamy>
            <zobrazitTipy>true</zobrazitTipy>
            <preferovanaSirka>1024</preferovanaSirka>
            <preferovanaVyska>768</preferovanaVyska>
            <menuBar plovouci="false">true</menuBar>
            <animaceIkon>true</animaceIkon>
            <barevneSchema>Bile</barevneSchema>
            <jazyk>CZ</jazyk>
        </rozhrani>
        <sit>
            <kontrolovatAktualizace priXSpusteni="10">true</kontrolovatAktualizace>
            <citacSpusteni>4</citacSpusteni>
        </sit>
        <tisk>
            <rozliseni jednotka="DPI">600</rozliseni>
            <barevnost>Cernobile</barevnost>
            <format>A5</format>
            <orientace>Vyska</orientace>
            <kvalita>Nizka</kvalita>
            <duplex>true</duplex>
            <okraje uvodniStranka="false" zobrazitOkraje="false">
                <vlevo jednotka="mm">15</vlevo>
                <vpravo jednotka = "mm">15</vpravo>
                <nahore jednotka="mm">20</nahore>
                <dole jednotka="mm">20</dole>
            </okraje>
            <barevnyModel>CMYK</barevnyModel>
            <korekce>
                <jas>0.75</jas>
                <kontrast>0.16</kontrast>
                <gamma>0.55</gamma>
            </korekce>
            <orezoveZnacky>true</orezoveZnacky>
            <cislaStran>false</cislaStran>
            <pocetKopii>10</pocetKopii>
        </tisk>
        <pocetZpracovavanychVlaken>8</pocetZpracovavanychVlaken>
        <komprimovatVystup format="zip" miraKomprese="5">true</komprimovatVystup>
        <povolitPluginy>false</povolitPluginy>
    </nastaveni>
    <nastaveni>
        <rozhrani>
            <font>
                <standardni>
                    <nazev>Helvetica</nazev>
                    <velikost>20</velikost>
                    <popredi typ="hex">#2E1FE6</popredi>
                    <pozadi typ="hex">#141415</pozadi>
                    <styl>Normalni</styl>
                    <zarovnani>Stred</zarovnani>
                </standardni>
                <vybrano>
                    <nazev>Consolas</nazev>
                    <velikost>16</velikost>
                    <popredi typ="hex">#242418</popredi>
                    <pozadi typ="hex">#15E1D2</pozadi>
                    <styl>Kurziva</styl>
                    <zarovnani>Vpravo</zarovnani>
                </vybrano>
            </font>
            <zaznamy>
                <maxPocetNaStranku>1000</maxPocetNaStranku>
                <radit>true</radit>
                <typRazeni>Sestupne</typRazeni>
                <metodaVystupu>CSV</metodaVystupu>
                <povolitObrazky zobrazitPopisek="true">true</povolitObrazky>
                <zakladniMena>CZK</zakladniMena>
                <zalamovaniRadku zobrazitSymbol="true">true</zalamovaniRadku>
                <znakovaSada>UTF-16</znakovaSada>
                <cislovatZaznamy start="100">true</cislovatZaznamy>
            </zaznamy>
            <zobrazitTipy>false</zobrazitTipy>
            <preferovanaSirka>1600</preferovanaSirka>
            <preferovanaVyska>1000</preferovanaVyska>
            <menuBar plovouci="false">false</menuBar>
            <animaceIkon>false</animaceIkon>
            <barevneSchema>Bile</barevneSchema>
            <jazyk>EN</jazyk>
        </rozhrani>
        <sit>
            <kontrolovatAktualizace priXSpusteni="10">true</kontrolovatAktualizace>
            <citacSpusteni>2</citacSpusteni>
        </sit>
        <tisk>
            <rozliseni jednotka="DPI">1200</rozliseni>
            <barevnost>Barva</barevnost>
            <format>A6</format>
            <orientace>Sirka</orientace>
            <kvalita>Standardni</kvalita>
            <duplex>true</duplex>
            <okraje uvodniStranka="false" zobrazitOkraje="true">
                <vlevo jednotka="cm">2.8</vlevo>
                <vpravo jednotka = "cm">2.8</vpravo>
                <nahore jednotka="cm">2.1</nahore>
                <dole jednotka="cm">2.1</dole>
            </okraje>
            <barevnyModel>HSV</barevnyModel>
            <korekce>
                <jas>0.5</jas>
                <kontrast>0.5</kontrast>
                <gamma>0.5</gamma>
            </korekce>
            <orezoveZnacky>true</orezoveZnacky>
            <cislaStran>false</cislaStran>
            <pocetKopii>1000</pocetKopii>
        </tisk>
        <pocetZpracovavanychVlaken>1</pocetZpracovavanychVlaken>
        <komprimovatVystup format="zip" miraKomprese="1">true</komprimovatVystup>
        <povolitPluginy>true</povolitPluginy>
    </nastaveni>
    <nastaveni>
        <rozhrani>
            <font>
                <standardni>
                    <nazev>Courier</nazev>
                    <velikost>12</velikost>
                    <popredi typ="hex">#161219</popredi>
                    <pozadi typ="hex">#121610</pozadi>
                    <styl>Kurziva</styl>
                    <zarovnani>Stred</zarovnani>
                </standardni>
                <vybrano>
                    <nazev>Courier</nazev>
                    <velikost>12</velikost>
                    <popredi typ="hex">#242412</popredi>
                    <pozadi typ="html">#152016</pozadi>
                    <styl>Kurziva</styl>
                    <zarovnani>Vlevo</zarovnani>
                </vybrano>
            </font>
            <zaznamy>
                <maxPocetNaStranku>50</maxPocetNaStranku>
                <radit>false</radit>
                <typRazeni>Sestupne</typRazeni>
                <metodaVystupu>PDF</metodaVystupu>
